package com.stryvesolutions.mft.mftexercise.web.mappers;

import com.stryvesolutions.mft.mftexercise.domain.Exercise;
import com.stryvesolutions.mft.mftexercise.web.model.ExerciseDTO;
import org.mapstruct.Mapper;

// mapper annotation tells mapstruct processor to create an implementation of the below interface.
@Mapper(uses = DateMapper.class)
public interface ExerciseMapper {

    // Autogenerated code will map exercise object to ExerciseDTO
    // @Mapping(source = "firstName", target = "name") can be used if the field names do not match.
    ExerciseDTO convertToExerciseDTO(Exercise exercise);

    Exercise convertToExercise(ExerciseDTO exerciseDTO);

}
